<div class="padded column container100vh ycenter istop rgap32">
  <h1>IKS and Heritage Association (IKSHA) is a registered nonprofit organization (section-8 company) dedicated to enriching the scholarship within various domains of Indian Knowledge Systems (IKS).</h1>
  <div class="column rgap8 bordtop ptop32">
    <h6 class="themed">Our Premise</h6>
    <div class="grid two cgap32 rgap16">
    <p>Our unwavering commitment to advance IKS arises from profound cognitive considerations. It is widely recognized that Indian traditions have evolved various avenues for contemplating human conditions, thereby yielding knowledge over millennia. These contemplative and practice-based pursuits manifest either through a succession of textual traditions or performative expressions, and at times, a combination of both, spanning languages such as Sanskrit, Prakrit, Pali, and numerous regional languages. Each reflective tradition has forged distinctive methods, procedures, and theories to interpret the intricacies of the world. The amalgamation of these intricate and diverse traditions collectively forms a realm of knowledge broadly identified as IKS. Given the extraordinary intellectual achievements of Indian traditions across an extensive spatial and temporal spectrum, the resultant knowledge holds universal significance. Therefore, it possesses a legitimate entitlement to be incorporated into the instructional, learning, and reflective practices of any educational institution.</p>
    <p>IKSHA, where our commitment revolves around knowledge creation, and creating a condition of possibility of pursuit of happiness (Aananda) by every individual, our emphasis on IKS as a distinct domain becomes particularly pertinent. In the contemporary educational landscape, the knowledge produced by the universities, Higher educational institutions (HEIs), owing to its disciplinary and methodological commitments, tend to overlook or inadequately accommodate the scholarly reflections historically generated by Indian traditions. IKSHA, devoted to knowledge creation and to build individuals who have deeper commitments to Indian ways of being, aims to rectify the exclusionary nature of prevailing contemporary knowledge systems. By integrating reflections from Indian traditions, we strive to make our educational landscape more inclusive, thus presenting a unique endeavor to infuse diversity, pluralism, and inclusivity into the educational enterprise. This approach is not merely an attempt to address historical oversights but, importantly, a concerted effort to create a more diverse and inclusive academic environment. Through such a pluralistic perspective, IKSHA seeks to contribute to the global discourse, fostering a culture of deliberation for a better world.</p>
    </div>
  </div>
  <div class="column rgap8 bordtop ptop32">
    <h6 class="themed">Purpose</h6>
    <p>To establish a platform for Excellence aimed at positioning IKS as an alternative to the dominant paradigm across the multiple domains.</p>
  </div>
  <div class="column rgap8 bordtop ptop32">
    <h6 class="themed">Goals</h6>
    <ol>
      <li>To mainstream IKS by establishing appropriate ecosystem to produce knowledge globally.</li>
      <li>Capacity building and future generation scholarship with rigor through supporting research initiatives.</li>
      <li>Institutionalization of IKS academically through collaboration with individuals and institutions in India and abroad.</li>
      <li>Training individuals and general public to have immersive experiences in IKS.</li>
      <li>Outreach to stakeholders in Business, Government, and society.</li>
    </ol>
  </div>
  <div class="column rgap8 bordtop ptop32">
    <h6 class="themed">Specific Objectives</h6>
    <ol>
      <li>108 PhD: to establish future generation of scholarship through supporting PhD and Postdoctoral work.</li>
      <li>Journal: To facilitating IKS activity by establishing a high-quality journal for scholarly expressions and conversations.</li>
      <li>Annual Academic Conference: To establish a platform for intergenerational conversations among academic scholars for quality and initiating younger generation scholars into research.</li>
      <li>Annual IKS Conclave: To build a forum for bringing all IKS stakeholders (Practitioners, Scholars, Spiritual leaders, Industry, Government etc) together to prioritise important issues concerning IKS.</li>
      <li>Documentation: To build appropriate databases and networks through documentation.</li>
      <li>Domain Specific Groups: To bring scholars across the domains together to develop courses, formulate research questions and prioritise the agendas for the respective domains of IKS.</li>
    </ol>
  </div>
  <div class="column rgap16 bordtop ptop32">
	<h1>The IKSHA Team</h1>
	<div class="grid four cgap32 rgap32 stay2">
		<div>
			<p class="bold">Manohar Shinde</p>
			<p class="small greyed">Chief Patron</p>
		</div>
		<div>
			<p class="bold">Srikant Kumar</p>
			<p class="small greyed">Co-ordinator</p>
		</div>
		<div>
			<p class="bold">M.S.Chaitra Mathighatta</p>
			<p class="small greyed">Foundation for Study of Indian Culture, Bengaluru</p>
		</div>
		<div>
			<p class="bold">Nomesh Bolia</p>
			<p class="small greyed">IIT Delhi</p>
		</div>
		<div>
			<p class="bold">Anil Kumar Gourishetty</p>
			<p class="small greyed">IIT Roorkee</p>
		</div>
		<div>
			<p class="bold">Mohan Raghavan</p>
			<p class="small greyed">IIT Hyderabad</p>
		</div>
		<div>
			<p class="bold">Jyotirmaya Tripathy</p>
			<p class="small greyed">IIT Madras</p>
		</div>
		<div>
			<p class="bold">Ashwini B. Desai</p>
			<p class="small greyed">Foundation for Study of Indian Culture, Bengaluru</p>
		</div>
		<div>
			<p class="bold">Raghava Krishna</p>
			<p class="small greyed">Bṛhat, Hyderabad</p>
		</div>
		<div>
			<p class="bold">G V Shivakumar</p>
			<p class="small greyed">INDIC Academy, Bengaluru</p>
		</div>
		<div>
			<p class="bold">Yugank Goyal</p>
			<p class="small greyed">FLAME University, Pune</p>
		</div>
		<div>
			<p class="bold">Harsha Simha</p>
			<p class="small greyed">IIST, Thiruvananthapuram</p>
		</div>
		<div>
			<p class="bold">Sampadananda Mishra</p>
			<p class="small greyed">Rishihood University</p>
		</div>
		<div>
			<p class="bold">Arnab Bhattacharya</p>
			<p class="small greyed">IIT Kanpur</p>
		</div>
		<div>
			<p class="bold">T. V. Bharat</p>
			<p class="small greyed">IIT Guwahati</p>
		</div>
		<div>
			<p class="bold">P. N. Ravindra</p>
			<p class="small greyed"> NIMHANS</p>
		</div>
		<div>
			<p class="bold">Prashant P. Dharmadhikari</p>
			<p class="small greyed">Central University of Gujrat</p>
		</div>
		<div>
			<p class="bold">Amaranadha Reddy Manchuri</p>
			<p class="small greyed">Samskruti Foundation</p>
		</div>
	</div>
  </div>
</div>